services:
  db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: ["postgres","-c","timezone=UTC"]
    restart: unless-stopped
